apiVersion: v1
kind: Namespace
metadata:
  name: test-ingress
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.25
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.25
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.25
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test-ingress
spec:
  rules:
    - host: foo1.bar.com
      http:
        paths:
          - backend:
              service:
                name: nginx-ingress-svc
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-svc
  namespace: test-ingress
  labels:
    k8s-app: nginx-app-ingress
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    k8s-app: nginx-app-ingress
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-ingress
  namespace: test-ingress
spec:
  replicas: 2
  selector:
    k8s-app: nginx-app-ingress
  template:
    metadata:
      labels:
        k8s-app: nginx-app-ingress
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: testcontainer
          image: shylajarancher19/mytestcontainer:unprivileged
          ports:
            - containerPort: 8080
