name: Qase Run Create
on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Provide the versions'
        required: true
        default: 'v1.29.0,v1.30.0,v1.31.0,v1.32.0'
      rcs:
        description: 'Provide the list of RCs to run'
        required: true
        default: 'v1.29.0-rc1,v1.30.0-rc1,v1.31.0-rc1,v1.32.0-rc1'

permissions:
  contents: read

jobs:
  create_qase_run:
    name: 'Create Qase Run'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout distros
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Perm for Script
        run: chmod +x ./scripts/qase-run.sh


 